version: "3.1"
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: A1234
    ports:
      - "3306:3306"

  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
